### ISSUE TITLE
inference on modd2 dataset

### ISSUE THREAD

**Issue by bilgecanpullinen** [lojzezust/WaSR#2]
did you evaluate your models on the modd2 dataset?

**Comment by lojzezust** [comment]
No, the models of this re-implementation have not been evaluated on MODD2. However, we expect the results to be similar to the results of the original implementation reported in [1].

Reference
[1] Bovcon, B., & Kristan, M. (2021). WaSR--A Water Segmentation and Refinement Maritime Obstacle Detection Network. IEEE Transactions on Cybernetics

**Comment by bilgecanpullinen** [comment]
Okay, thank you for the quick response.
