### ISSUE TITLE
Wasr-T code release

### ISSUE THREAD

**Issue by sevocrear** [lojzezust/WaSR#3]
Good afternoon, could you tell, please, when you'll release code for the new Wasr-T neural net? https://arxiv.org/pdf/2203.05352.pdf

**Comment by lojzezust** [comment]
We plan to release the code for WaSR-T soon (during the summer). I will let you know once the code is available.

**Comment by lojzezust** [comment]
I'm happy to let you know, that the code for WaSR-T is now available. You can find it here: https://github.com/lojzezust/WaSR-T
