### ISSUE TITLE
Prediction with IMU model

### ISSUE THREAD

**Issue by gkstjsals** [lojzezust/WaSR#4]
Hello, 
I wanted to run predict.py with IMU model, so i followed tutorial in README.

python predict.py \
--dataset_config configs/examples.yaml \
--model wasr_resnet101_imu \
--weights path/to/model/weights.pth \
--output_dir output/predictions

But I met the error below.

Traceback (most recent call last):
  File "/snap/pycharm-community/293/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/WaSR/wasr/models.py", line 63, in forward
    features['imu_mask'] = x['imu_mask']
KeyError: 'imu_mask'

How can i fix it?

**Comment by lojzezust** [comment]
Have you maybe edited the data config file? This is an error you would see, if you remove the `imu_dir` entry from the data configuration file. The `imu_dir` is the location of IMU horizon masks (1s for under horizon and 0s for above horizon) for each input image (as in the included examples).

If you do not have the IMU data for your images, try using the no-IMU version of the model instead. There you only need images.

**Comment by gkstjsals** [comment]
I was using a customed config file. 
Thank you for your quick reply!
